/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function connectionCloseSync(connHandle: number): void

export declare function connectionExecuteSync(connHandle: number, psHandle: number, paramsJson: string): number

export declare function connectionLoadArrowAsync(connHandle: number, batchesJson: string, optionsJson: string): Promise<void>

export declare function connectionLoadArrowSync(connHandle: number, batchesJson: string, optionsJson: string): void

export declare function connectionPrepareSync(connHandle: number, statement: string): number

export declare function connectionQueryAsync(connHandle: number, statementHex: string): Promise<number>

export declare function connectionQuerySync(connHandle: number, statement: string): number

export declare function databaseCloseSync(dbHandle: number): void

export declare function databaseConnectSync(dbHandle: number, numThreads: number): number

export declare function databaseCreateAsync(path: string): Promise<number>

export declare function databaseCreateSync(path: string): number

export declare function getAllArrowChunksAsync(resultHandle: number, chunkSize: number): Promise<Array<string>>

export declare function getAllArrowChunksBinaryAsync(resultHandle: number, chunkSize: number): Promise<Array<Buffer>>

/**
 * Temporary stub topology export for zero-copy bridge wiring.
 *
 * Returns an empty topology shape; real data will be provided once
 * Ladybug exposes a graph/topology API.
 */
export declare function getTopology(): NativeTopology

export interface NativeTopology {
  sources: Int32Array
  targets: Int32Array
  dictionary: Array<string>
}

/** Simple placeholder function used by tests to verify that the addon loads. */
export declare function placeholder(): number

export declare function preparedStatementCloseSync(psHandle: number): void

export declare function preparedStatementGetErrorMessageSync(psHandle: number): string

export declare function preparedStatementIsSuccessSync(psHandle: number): boolean

export declare function queryResultCloseSync(resultHandle: number): void

export declare function queryResultGetArrowSchemaBinarySync(resultHandle: number): Buffer

export declare function queryResultGetArrowSchemaSync(resultHandle: number): string

export declare function queryResultGetColumnDataTypesSync(resultHandle: number): Array<string>

export declare function queryResultGetColumnNamesSync(resultHandle: number): Array<string>

export declare function queryResultGetNextArrowChunkBinarySync(resultHandle: number, chunkSize: number): Buffer

export declare function queryResultGetNextArrowChunkSync(resultHandle: number, chunkSize: number): string

export declare function queryResultGetNextRowSync(resultHandle: number): string

export declare function queryResultGetNumTuplesSync(resultHandle: number): number

export declare function queryResultHasNextSync(resultHandle: number): boolean
